// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcE98KYZa-VgnYxihjDsJ6T5uowMvgSr4',
    appId: '1:136266040329:ios:3d17395e08bf8d5927e4d8',
    messagingSenderId: '136266040329',
    projectId: 'birjiskhatoon-ee51b',
    storageBucket: 'birjiskhatoon-ee51b.firebasestorage.app',
    iosBundleId: 'com.example.birjisKhatoon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQZnqiJZ-ohTI8lpsZ3-avtbVjHu30pi8',
    appId: '1:136266040329:web:659d1bb9f040ead827e4d8',
    messagingSenderId: '136266040329',
    projectId: 'birjiskhatoon-ee51b',
    authDomain: 'birjiskhatoon-ee51b.firebaseapp.com',
    storageBucket: 'birjiskhatoon-ee51b.firebasestorage.app',
    measurementId: 'G-C0TVNKJEG3',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQZnqiJZ-ohTI8lpsZ3-avtbVjHu30pi8',
    appId: '1:136266040329:web:659d1bb9f040ead827e4d8',
    messagingSenderId: '136266040329',
    projectId: 'birjiskhatoon-ee51b',
    authDomain: 'birjiskhatoon-ee51b.firebaseapp.com',
    storageBucket: 'birjiskhatoon-ee51b.firebasestorage.app',
    measurementId: 'G-C0TVNKJEG3',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcE98KYZa-VgnYxihjDsJ6T5uowMvgSr4',
    appId: '1:136266040329:ios:3d17395e08bf8d5927e4d8',
    messagingSenderId: '136266040329',
    projectId: 'birjiskhatoon-ee51b',
    storageBucket: 'birjiskhatoon-ee51b.firebasestorage.app',
    iosBundleId: 'com.example.birjisKhatoon',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8O8Tg9GMmtfuXdjtEsKvVwB9yz6iCvtg',
    appId: '1:136266040329:android:7d3781ec7aa3ef7227e4d8',
    messagingSenderId: '136266040329',
    projectId: 'birjiskhatoon-ee51b',
    storageBucket: 'birjiskhatoon-ee51b.firebasestorage.app',
  );

}